### ISSUE TITLE
please add configure/use paragraphs

### ISSUE THREAD

**Issue by Albirew** [DLMSweet/MDRSS#1]
from all mangadex rss feed generator i found, yours seems to be the best made one.
Is it possible to add and explain installation, configuration and use (use of app.secret_key, what and where to edit for embedded http server port (if editable), how to install and start, etc.) in readme.md file?

**Comment by DLMSweet** [comment]
I've added some details on setting this up. It's been a hot minute since I last set it up, since I've just had it running. 
Let me know if that helps.

**Comment by DLMSweet** [comment]
Regarding Flask's secret key, it has to do with their cookie signing. You can set it to whatever you want. 
It should basically just be a random string. 

You can change what port Hypercorn listens on by editing the systemd unit file. The options you're probably looking for are:
```
  -b BINDS, --bind BINDS
                        The TCP host/address to bind to. Should be either host:port, host, unix:path or fd://num, e.g. 127.0.0.1:5000, 127.0.0.1, unix:/tmp/socket or fd://33 respectively.
```

I'd also recommend setting `--access-logfile -` to have systemd handle the output. I'll add that to the example.

**Comment by Albirew** [comment]
many thanks!
i will install it on the weekend on a new VM (or maybe i'll make a docker container for it, dunno yet), i'll let you know then =)
